const path = require("path")
const helmet = require("helmet")
const express = require("express")
const passport = require("passport")
const bodyParser = require("body-parser")
const compression = require("compression")

const config = require("./config")
const createRoutes = require("./routes")
const createLoggers = require("./logger")
const setupDb = require("./db/connect")
const setupPassport = require("./passport")

const routes = createRoutes(config)
const { logger, middleware: loggingMiddleware } = createLoggers(config)

setupDb(config)
setupPassport(config)

express()
  .use(bodyParser.urlencoded({ extended: false, limit: "4mb" }))
  .use(bodyParser.json({ limit: "4mb" }))
  .use(loggingMiddleware)
  .set("views", path.join(__dirname, "views"))
  .set("view engine", "jade")
  .use(passport.initialize())
  .use(compression())
  .use(helmet())
  .use("/", routes)
  .use("/images", express.static(`${config.assetsDir}/images`))
  .use("/styles", express.static(`${config.assetsDir}/styles`))
  .use("/js", express.static(`${config.assetsDir}/js`))
  .listen(config.port, "0.0.0.0", () => logger.info(`Express server listening on port ${config.port}`))
